apiVersion: apps/v1
kind: Deployment
metadata:
  name: oanda-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oanda-live
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oanda-live
        version: v1
    spec:
      containers:
        - image: matrixacr.azurecr.io/oanda-live:v1
          imagePullPolicy: Always
          name: oanda-live
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oanda-live
  name: oanda-live
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: oanda-live
  sessionAffinity: None
  type: LoadBalancer
