
class env:
    RUN_MODE_TESTING = "RUN_MODE_TESTING"
    RUN_MODE_LIVE = "RUN_MODE_LIVE"
    RUN_MODE = "RUN_MODE"
    OANDA_TOKEN = "OANDA_TOKEN"
    OANDA_DEFAULT_ACCOUNT = "OANDA_DEFAULT_ACCOUNT"
    OANDA_TRADE_DOMAIN = "OANDA_TRADE_DOMAIN"
    OANDA_PRICE_EXCHANGE = "OANDA_PRICE_EXCHANGE"
    OANDA_PRICE_QUEUE_1 = "OANDA_PRICE_QUEUE_1"
    OANDA_PRICE_QUEUE_2 = "OANDA_PRICE_QUEUE_2"
    OANDA_STREAM_DOMAIN = "OANDA_STREAM_DOMAIN"
    MONGODB_FULL_URL = "MONGODB_FULL_URL"
    REDIS_DOMAIN = "REDIS_DOMAIN"
    RABBIT_DOMAIN = "RABBIT_DOMAIN"
    RABBIT_USERNAME = "RABBIT_USERNAME"
    RABBIT_PASSWORD = "RABBIT_PASSWORD"


class trd:
    LONG_TRADE = "LONG_TRADE"
    SHORT_TRADE = "SHORT_TRADE"
    NO_TRADE = "NO_TRADE"
    PREPARE_SHORT = "PREPARE_SHORT"
    PREPARE_LONG = "PREPARE_LONG"
